# KumuluzEE application configuration
kumuluzee:
  datasources:
    - jndi-name: jdbc/MoviesDataSource
      connection-url: jdbc:h2:mem:movies
      username: 
      password: 
      pool:
        max-size: 20
  server:
    http:
      port: 8080

movies:
  service-images:
    url: http://localhost:8081/images
  http-cache:
    max-age: 60
  counters:
    file-system:
      path: c:/temp/