# KumuluzEE application configuration
kumuluzee:
  datasources:
    - jndi-name: jdbc/ImagesDataSource
      connection-url: jdbc:h2:mem:images
      username: 
      password: 
      pool:
        max-size: 20
  server:
    http:
      port: 8081

movies:
  service-movies:
    url: http://localhost:8080/movies
  counters:
    file-system:
      path: c:/temp/
  image:
    upload:
      path: c:/temp